services:
  db:
    image: postgres:15-alpine
    container_name: loka_verkefni
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: loka_verkefni_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib.postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: